"""Constants for URLGuard feature extraction."""

SUSPICIOUS_TLDS: set[str] = {
    "xyz",
    "tk",
    "ml",
    "ga",
    "cf",
    "gq",
    "top",
    "pw",
    "cc",
    "info",
    "click",
    "link",
    "online",
    "site",
    "website",
    "space",
    "live",
    "stream",
    "download",
}

BRAND_NAMES: set[str] = {
    "paypal",
    "google",
    "facebook",
    "amazon",
    "apple",
    "microsoft",
    "netflix",
    "instagram",
    "twitter",
    "linkedin",
    "dropbox",
    "chase",
    "wellsfargo",
    "bankofamerica",
    "citibank",
    "hdfc",
    "sbi",
    "icici",
    "paytm",
    "phonepe",
    "razorpay",
}

FEATURE_NAMES: list[str] = [
    "url_length",
    "domain_length",
    "path_length",
    "num_dots",
    "num_hyphens",
    "num_at_symbols",
    "num_query_params",
    "has_ip_address",
    "has_https",
    "tld_is_suspicious",
    "subdomain_depth",
    "path_depth",
    "has_brand_in_subdomain",
    "lexical_diversity",
    "digit_ratio",
]
